from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass, field
from pathlib import Path


class ConfigError(Exception):
    pass


@dataclass
class BarkConfig:
    device_key: str = ""
    server: str = "https://api.day.app"
    icon: str = ""
    sound: str = ""
    group: str = ""


@dataclass
class NtfyConfig:
    topic: str = ""
    server: str = "https://ntfy.sh"
    token: str = ""
    priority: int | None = 3
    tags: list[str] = field(default_factory=list)


@dataclass
class Config:
    backends: list[str] = field(default_factory=list)
    bark: BarkConfig | None = None
    ntfy: NtfyConfig | None = None
    source: str = ""  # path or "<env>" — for diagnostics


def default_config_path() -> Path:
    base = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    return Path(base) / "agentnotify" / "config.toml"


def load(path: Path | None = None) -> Config:
    """Load config from TOML file, then overlay environment variables.

    Missing file is fine — env-only configuration is supported.
    """
    cfg = Config()
    src: list[str] = []

    p = path or default_config_path()
    if p.exists():
        with open(p, "rb") as f:
            data = tomllib.load(f)
        cfg.backends = list(data.get("backends", []))
        if "bark" in data:
            b = data["bark"]
            cfg.bark = BarkConfig(
                device_key=b.get("device_key", ""),
                server=b.get("server", "https://api.day.app"),
                icon=b.get("icon", ""),
                sound=b.get("sound", ""),
                group=b.get("group", ""),
            )
        if "ntfy" in data:
            n = data["ntfy"]
            cfg.ntfy = NtfyConfig(
                topic=n.get("topic", ""),
                server=n.get("server", "https://ntfy.sh"),
                token=n.get("token", ""),
                priority=n.get("priority", 3),
                tags=list(n.get("tags", [])),
            )
        src.append(str(p))

    # Env overlay.
    env_backends = os.environ.get("AGENTNOTIFY_BACKENDS")
    if env_backends:
        cfg.backends = [b.strip() for b in env_backends.split(",") if b.strip()]

    if any(os.environ.get(k) for k in ("AGENTNOTIFY_BARK_KEY", "AGENTNOTIFY_BARK_SERVER")):
        cfg.bark = cfg.bark or BarkConfig()
        cfg.bark.device_key = os.environ.get("AGENTNOTIFY_BARK_KEY", cfg.bark.device_key)
        cfg.bark.server = os.environ.get("AGENTNOTIFY_BARK_SERVER", cfg.bark.server)
        if "bark" not in cfg.backends:
            cfg.backends.append("bark")

    if any(os.environ.get(k) for k in (
        "AGENTNOTIFY_NTFY_TOPIC",
        "AGENTNOTIFY_NTFY_SERVER",
        "AGENTNOTIFY_NTFY_TOKEN",
    )):
        cfg.ntfy = cfg.ntfy or NtfyConfig()
        cfg.ntfy.topic = os.environ.get("AGENTNOTIFY_NTFY_TOPIC", cfg.ntfy.topic)
        cfg.ntfy.server = os.environ.get("AGENTNOTIFY_NTFY_SERVER", cfg.ntfy.server)
        cfg.ntfy.token = os.environ.get("AGENTNOTIFY_NTFY_TOKEN", cfg.ntfy.token)
        if "ntfy" not in cfg.backends:
            cfg.backends.append("ntfy")

    if not src:
        src.append("<env>")
    cfg.source = ", ".join(src)
    return cfg


INIT_TEMPLATE = '''\
# AgentNotification configuration — generated by `agentnotify init`.

backends = {backends!r}

[bark]
device_key = "{bark_key}"
server = "{bark_server}"
# Default icon for manual `agentnotify send` calls. Per-agent hooks
# (claude-stop, codex-stop, kimi-stop, …) override this with their own
# branded icon; leave empty for Bark's default app icon, or set a URL
# you'd like all manual sends to use.
icon = ""
group = "agent"

[ntfy]
topic = "{ntfy_topic}"
server = "{ntfy_server}"
priority = 3
tags = ["robot"]
'''


def write_initial(path: Path, *, backends: list[str], bark_key: str, bark_server: str,
                  ntfy_topic: str, ntfy_server: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # TOML spec mandates UTF-8 — write_text defaults to the OS locale
    # encoding on Windows (GBK/CP936 on zh-CN), which then fails to
    # round-trip through tomllib.load. Force UTF-8 here and everywhere
    # else we touch agent config files.
    path.write_text(INIT_TEMPLATE.format(
        backends=backends,
        bark_key=bark_key,
        bark_server=bark_server,
        ntfy_topic=ntfy_topic,
        ntfy_server=ntfy_server,
    ), encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass
